use_frameworks!
platform :ios, '12.0'

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
end

target 'Monri_Example' do
  pod 'Monri', :path => '../'

  target 'Monri_Tests' do
    inherit! :search_paths

    use_frameworks!
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 9.0.1'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end



